version: '2'
services:
  redis:
    image: redis
  db:
    image: postgres:9.4
    environment: POSTGRES_USER:postgres POSTGRES_PASSWORD:postgres
  vote:
    build: ./vote
    ports:
      - 5000:80
    links:
      ## Is now replaced by depends_on
      - redis
  result:
    build: ./result
    ports:
      - 5001:80
    links:
      - db
  worker:
    build: ./worker
    links:
      - db
      - redis
  app:
    image: arkapatra31/basic_node_docker_deployed
    ports:
      - 5000:5000
